version: "3.9"
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: python server.py
  database:
    build: ./database
    ports:
      - "19530:19530"
      - "9091:9091"
    volumes:
      - .:/app
    command: ["milvus", "run", "standalone"]
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000