version: "3.9"
services:
  program:
    build: .
    volumes:
      - .:/app
    command: python /app/program.py

# Q. what does a docker-compose.yml file do?
# A. it tells docker-compose to build an image from the Dockerfile in the current directory
# Q. what if I want to use more than one Dockerfile such as a Dockerfile for the program and a Dockerfile for the database?
# A. here's how to do that:
version: "3.9"
services:
  program:
    build: .
    volumes:
      - .:/app
    command: python /app/program.py
  database:
    build: .
    volumes:
      - .:/app
    command: python /app/database.py
    
# Q. do the program and the database need to have their own Dockerfiles?
# A. no, they can share the same Dockerfile
# Q. what if I want to use different Dockerfiles?
# A. here's how to do that:
version: "3.9"
services:
  program:
    build: ./program
    volumes:
      - .:/app
    command: python /app/program.py
  database:
    build: ./database
    volumes:
      - .:/app
    command: python /app/database.py

# A. where program and database are directories containing Dockerfiles
# A. example file strucutre:
.
├── database
│   ├── Dockerfile
│   └── database.py
├── program
│   ├── Dockerfile
│   └── program.py
└── docker-compose.yml
